### ISSUE TITLE
Query related to GitHub Pages

### ISSUE THREAD

**Issue by Rajayashwanth-R** [ydamni/cloud-is-free#5]
Hi ydamni,
I hope you are doing well. Your work on Cloud-is-free is beautiful and contains good and valuable information. I am a security analyst. And I need to contribute to the community like you. I tried to create a website like yours and Learn-to-cloud (By GPS) using GitHub page for people to learn Cyber Security for free. But I am facing an issue. The sidebar.md and coverpage.md are not working (Not appearing in my website). I have attached the Screenshot for your reference. Please help me out with this.

Screenshot: ![Capture](https://user-images.githubusercontent.com/46133548/165290396-275ee34a-404b-4d32-b01c-42e467cf470f.PNG)

Link for GitHub Pages: https://soc-cy.github.io/Learn_Cybersecurity/#/
Repo: https://github.com/soc-cy/Learn_Cybersecurity

Have a nice day!
Thank you for your time and effort.

**Comment by ydamni** [comment]
Hi Raja,

I answered the email you sent me on contact@cloudisfree.com, you have everything you need inside the email.

Great initiative from you to create a website that focuses on Cybersecurity.
Good luck in your work!

Sincerely,
ydamni
